// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_urmpJoUTn45U-yG3fPjjWudDM1-D2M',
    appId: '1:627830961409:web:8aa8afa13b6e628f649700',
    messagingSenderId: '627830961409',
    projectId: 'seboagence-7b74b',
    authDomain: 'seboagence-7b74b.firebaseapp.com',
    storageBucket: 'seboagence-7b74b.firebasestorage.app',
    measurementId: 'G-GL815PZXDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_urmpJoUTn45U-yG3fPjjWudDM1-D2M',
    appId: '1:627830961409:android:8aa8afa13b6e628f649700',
    messagingSenderId: '627830961409',
    projectId: 'seboagence-7b74b',
    storageBucket: 'seboagence-7b74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_urmpJoUTn45U-yG3fPjjWudDM1-D2M',
    appId: '1:627830961409:ios:8aa8afa13b6e628f649700',
    messagingSenderId: '627830961409',
    projectId: 'seboagence-7b74b',
    storageBucket: 'seboagence-7b74b.firebasestorage.app',
    iosBundleId: 'com.example.seboAgency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_urmpJoUTn45U-yG3fPjjWudDM1-D2M',
    appId: '1:627830961409:ios:8aa8afa13b6e628f649700',
    messagingSenderId: '627830961409',
    projectId: 'seboagence-7b74b',
    storageBucket: 'seboagence-7b74b.firebasestorage.app',
    iosBundleId: 'com.example.seboAgency',
  );
}
